// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function makeNode() {
  return {
          isEndOfWord: false,
          children: undefined
        };
}

function insert(root, word) {
  if (word === "") {
    return {
            isEndOfWord: true,
            children: root.children
          };
  }
  var firstChar = word.substring(0, 1);
  var restOfWord = word.substring(1, word.length);
  var node = Belt_MapString.get(root.children, firstChar);
  var childNode = node !== undefined ? node : ({
        isEndOfWord: false,
        children: undefined
      });
  var updatedChild = insert(childNode, restOfWord);
  return {
          isEndOfWord: root.isEndOfWord,
          children: Belt_MapString.set(root.children, firstChar, updatedChild)
        };
}

function search(_root, _word) {
  while(true) {
    var word = _word;
    var root = _root;
    if (word === "") {
      return root.isEndOfWord;
    }
    var firstChar = word.substring(0, 1);
    var restOfWord = word.substring(1, word.length);
    var childNode = Belt_MapString.get(root.children, firstChar);
    if (childNode === undefined) {
      return false;
    }
    _word = restOfWord;
    _root = childNode;
    continue ;
  };
}

function startsWith(_root, _prefix) {
  while(true) {
    var prefix = _prefix;
    var root = _root;
    if (prefix === "") {
      return true;
    }
    var firstChar = prefix.substring(0, 1);
    var restOfPrefix = prefix.substring(1, prefix.length);
    var childNode = Belt_MapString.get(root.children, firstChar);
    if (childNode === undefined) {
      return false;
    }
    _prefix = restOfPrefix;
    _root = childNode;
    continue ;
  };
}

function make() {
  return {
          isEndOfWord: false,
          children: undefined
        };
}

var Trie = {
  makeNode: makeNode,
  insert: insert,
  search: search,
  startsWith: startsWith,
  make: make
};

export {
  Trie ,
}
/* No side effect */
